token: "lip_Lm1j499oMO6H9SuBmBEC"

engines:
  bullet:
    dir: "./engines"
    name: "sf"
    path: "./engines/sf" # set to your arm64 binary
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 19.5
    uci_options:
      Threads: 4
      Hash: 516
      UCI_ShowWDL: true
      Move Overhead: 100
    limits: {}

  standard:
    dir: "./engines"
    name: "sf"
    path: "./engines/sf"
    ponder: true
    silence_stderr: true
    move_overhead_multiplier: 1.0
    auto_tune: true
    uci_options:
      Threads: 4 # Maximum Threadripper power for longer games.
      Hash: 516 # Massive hash for deep calculation.
      UCI_ShowWDL: true
      Move Overhead: 100
    limits: {}

  variants: # Engine used for variants when no suitable special engine is configured.
    dir: "./engines" # Directory containing the engine.
    name: "fairy-stockfish" # Binary name of the engine to use.
    ponder: true # Think on opponent's time.
    silence_stderr: false # Suppresses stderr output.
    move_overhead_multiplier: 1.0 # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    uci_options: # Arbitrary UCI options passed to the engine.
      Threads: 4 # Max CPU threads the engine can use.
      Hash: 256 # Max memory (in megabytes) the engine can allocate.
      Move Overhead: 100 # Increase if your bot flags games too often.
      Use NNUE: true
      EvalFile: "3check-cb5f517c228b.nnue:antichess-dd3cbe53cd4e.nnue:atomic-2cf13ff256cc.nnue:crazyhouse-8ebf84784ad2.nnue:horde-28173ddccabe.nnue:kingofthehill-978b86d0e6a4.nnue:racingkings-636b95f085e3.nnue"
    limits: # Limits that end the move calculation early.
    #   time: 5.0 # Max time per move in seconds.
    #   depth: 26 # Max depth per move.
    #   nodes: 4000000 # Max nodes per move.

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

syzygy:
  standard:
    enabled: true
    paths:
      - "./syzygy"
    max_pieces: 5
    probe_depth: 1
    instant_play: true
  # antichess:
  #   enabled: false # Activate local syzygy endgame tablebases.
  #   paths: # Paths to local syzygy endgame tablebases.
  #     - "./antichess-syzygy"
  #   max_pieces: 6 # Count of max pieces in the local syzygy endgame tablebases.
  #   instant_play: true # Whether the bot should play directly from syzygy without engine if possible.
  # atomic:
  #   enabled: false # Activate local syzygy endgame tablebases.
  #   paths: # Paths to local syzygy endgame tablebases.
  #     - "./atomic-syzygy"
  #   max_pieces: 6 # Count of max pieces in the local syzygy endgame tablebases.
  #   instant_play: true # Whether the bot should play directly from syzygy without engine if possible.

opening_books:
  enabled: true
  priority: 900
  books:
    standard_black:
      selection: best_move
      names:
        - Stay
        - Win
        - Black
    standard_white:
      selection: best_move
      names:
        - Stay
        - White
        - Black
        - Optimus

online_moves:
  opening_explorer:
    enabled: false
    priority: 300
    only_without_book: false
    use_for_variants: false
    min_time: 10
    timeout: 5
    min_games: 5
    only_with_wins: false
    selection: "performance"
    anti: false

  lichess_cloud:
    enabled: false
    priority: 800 # below opening_books (900) but above most online sources
    only_without_book: false
    use_for_variants: false
    min_eval_depth: 14 # stronger depth
    min_time: 5 # only use cloud when there's at least 5s left
    timeout: 4 # wait up to 4s for cloud answer

  chessdb:
    enabled: false
    priority: 800
    only_without_book: false
    min_candidates: 1
    min_time: 0
    timeout: 5
    selection: "best"

  online_egtb:
    enabled: true
    min_time: 20
    timeout: 3

offer_draw:
  enabled: true # Activate whether the bot should offer draw.
  score: 10 # Tighter draw threshold - only accept truly equal positions.
  consecutive_moves: 5 # More moves required before considering draw.
  min_game_length: 30 # Later draw offers to avoid early draws.
  against_humans: false # Activate whether these settings should apply against humans.
  allow_in_tournaments: true # Allow offering draws in tournaments even for 0.5+0 games. By default, draws are never offered in 0.5+0 games.
  accept_30_second_draws: false

resign:
  enabled: false # Enable resignation to avoid hopeless positions.
  score: -800 # Resign when clearly losing (8 pawns down).
  consecutive_moves: 8 # More moves to confirm truly lost position.
  against_humans: false

challenge:
  concurrency: 2
  max_takebacks: 0
  bullet_with_increment_only: false
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
  bot_modes:
    - rated
    - casual
  human_modes:
    - rated
    - casual

matchmaking:
  delay: 10
  timeout: 30
  selection: sequential
  types:
    hyper: { tc: 0.5+0 }
  optional_settings:
    rated: false
    variant: standard

messages:
  greeting: "Hey! I'm TacticalBot running on {engine}. Good luck!"
  goodbye: "Good game!"
  greeting_spectators: "Hey! I'm TacticalBot running on {engine}."
  goodbye_spectators: "Thanks for watching!"

whitelist: []
blacklist: []

books:
  HyperBullet: "./books/hyperbullet.bin"
  Bullet: "./books/bullet.bin"
  Blitz: "./books/big_blitz.bin"
  EngineTheory: "./books/engine_theory.bin"
  DefaultBook: "./books/DefaultBook.bin"
  PerfectBook: "./books/perfect_book.bin"
  StockfishBook: "./books/sfbook.bin"
  Optimus: "./books/OPTIMUS2502.bin"
  Stay: "./books/terimakichud.bin"
  White: "./books/white.bin"
  Black: "./books/black.bin"
  Win: "./books/win.bin"
