token: "tokenXXXXX"

engines:
  bullet:
    dir: "./engines"
    name: "stockfish-ubuntu-x86-64-avx2"
    path: "./engines/stockfish-ubuntu-x86-64-avx2" # set to your arm64 binary
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 21.0
    uci_options:
      Threads: 8
      Hash: 5120
      UCI_ShowWDL: true
      Move Overhead: 100
    limits: {}

  standard:
    dir: "./engines"
    name: "ShashChess39-x86-64-avx2"
    path: "./engines/ShashChess39-x86-64-avx2"
    ponder: true
    silence_stderr: false
    move_overhead_multiplier: 1.0
    uci_options:
      Threads: 8 # Max cores on GitHub Actions
      Hash: 8192 # 1 GB for deeper tactical calculation
      UCI_ShowWDL: true
      Move Overhead: 100 # Minimal overhead → fastest moves
    limits:

  chess960: # Engine used for standard chess and when no suitable special engine is configured.
    dir: "./engines" # Directory containing the engine.
    name: "ShashChess39-x86-64-avx2" # Binary name of the engine to use.
    ponder: true # Think on opponent's time.
    silence_stderr: false # Suppresses stderr output.
    move_overhead_multiplier: 20.0 # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    uci_options: # Arbitrary UCI options passed to the engine.
      Threads: 8 # Max CPU threads the engine can use.
      Hash: 4096 # Max memory (in megabytes) the engine can allocate.
      Move Overhead: 100 # Increase if your bot flags games too often.
    limits:

  variants: # Engine used for variants when no suitable special engine is configured.
    dir: "./engines" # Directory containing the engine.
    name: "fairy-stockfish-largeboard_x86-64-modern" # Binary name of the engine to use.
    ponder: true # Think on opponent's time.
    silence_stderr: false # Suppresses stderr output.
    move_overhead_multiplier: 1.0 # Increase if your bot flags games too often. Default move overhead is 1 second per 1 minute initital time.
    uci_options: # Arbitrary UCI options passed to the engine.
      Threads: 8 # Max CPU threads the engine can use.
      Hash: 8192 # Max memory (in megabytes) the engine can allocate.
      Move Overhead: 100 # Increase if your bot flags games too often.
      Use NNUE: true
      EvalFile: "3check-cb5f517c228b.nnue:antichess-dd3cbe53cd4e.nnue:atomic-2cf13ff256cc.nnue:crazyhouse-8ebf84784ad2.nnue:horde-28173ddccabe.nnue:kingofthehill-978b86d0e6a4.nnue:racingkings-636b95f085e3.nnue"
    limits: # Limits that end the move calculation early.
    #   time: 5.0 # Max time per move in seconds.
    #   depth: 26 # Max depth per move.
    #   nodes: 4000000 # Max nodes per move.

gaviota:
  enabled: false
  paths:
    - "/path/to/gaviota"
  max_pieces: 5

syzygy:
  standard:
    enabled: true
    paths:
      - "./syzygy"
    max_pieces: 5
    instant_play: true
  chess960:
    enabled: true # Activate local syzygy endgame tablebases.
    paths: # Paths to local syzygy endgame tablebases.
      - "./syzygy"
    max_pieces: 5 # Count of max pieces in the local syzygy endgame tablebases.
    instant_play: true # Whether the bot should play directly from syzygy without engine if possible.
  antichess:
    enabled: false # Activate local syzygy endgame tablebases.
    paths: # Paths to local syzygy endgame tablebases.
      - "./antichess-syzygy"
    max_pieces: 6 # Count of max pieces in the local syzygy endgame tablebases.
    instant_play: true # Whether the bot should play directly from syzygy without engine if possible.
  atomic:
    enabled: false # Activate local syzygy endgame tablebases.
    paths: # Paths to local syzygy endgame tablebases.
      - "./atomic-syzygy"
    max_pieces: 6 # Count of max pieces in the local syzygy endgame tablebases.
    instant_play: true # Whether the bot should play directly from syzygy without engine if possible.

opening_books:
  enabled: true
  priority: 900
  books:
    standard_black:
      selection: best_move
      names:
        - Stay
        - Win
        - Black
    standard_white:
      selection: best_move
      names:
        - Stay
        - White
        - Black
        - Optimus

online_moves:
  opening_explorer:
    enabled: false
    priority: 300
    only_without_book: false
    use_for_variants: false
    min_time: 10
    timeout: 5
    min_games: 5
    only_with_wins: false
    selection: "performance"
    anti: false

  lichess_cloud:
    enabled: false
    priority: 800 # below opening_books (900) but above most online sources
    only_without_book: false
    use_for_variants: false
    min_eval_depth: 14 # stronger depth
    min_time: 5 # only use cloud when there's at least 5s left
    timeout: 4 # wait up to 4s for cloud answer

  chessdb:
    enabled: false
    priority: 800
    only_without_book: false
    min_candidates: 1
    min_time: 0
    timeout: 5
    selection: "best"

  online_egtb:
    enabled: true
    min_time: 20
    timeout: 3

offer_draw:
  enabled: true # Activate whether the bot should offer draw.
  score: 10 # Tighter draw threshold - only accept truly equal positions.
  consecutive_moves: 5 # More moves required before considering draw.
  min_game_length: 30 # Later draw offers to avoid early draws.
  against_humans: false # Activate whether these settings should apply against humans.
  allow_in_tournaments: true # Allow offering draws in tournaments even for 0.5+0 games. By default, draws are never offered in 0.5+0 games.
  accept_30_second_draws: false

resign:
  enabled: true # Enable resignation to avoid hopeless positions.
  score: -800 # Resign when clearly losing (8 pawns down).
  consecutive_moves: 8 # More moves to confirm truly lost position.
  against_humans: false

matchmaking:
  delay: 60 # Time in seconds the bot must be idle before a new challenge is started.
  allow_matchmaking: true
  challenge_mode: rated
  timeout: 30
  selection: weighted_random
  types:
    bullet_0_5:
      enabled: true
      tc: "0.5+0"
      variant: standard
    blitz_3_0:
      enabled: true
      tc: "3+0"
      variant: standard
    rapid_8+0:
      enabled: true
      tc: "8+0"
      variant: standard
    0.5_chess960:
      enabled: true
      tc: "0.5+0"
      variant: chess960
    crazyhouse:
      enabled: true
      tc: "1+0"
      variant: crazyhouse
    threeCheck:
      enabled: true
      tc: "1+0"
      variant: threeCheck
    kingOfTheHill:
      enabled: true
      tc: "0.5+0"
      variant: kingOfTheHill
    atomic:
      enabled: true
      tc: "1+0"
      variant: atomic
    racingKings:
      enabled: true
      tc: "3+0"
      variant: racingKings
    antichess:
      enabled: true
      tc: "1+0"
      variant: antichess
    horde:
      enabled: true
      tc: "1+0"
      variant: horde

challenge: # Incoming challenges.
  concurrency: 1 # Number of games to play simultaneously.
  max_takebacks: 3 # Maximum number of takebacks granted to a human.
  bullet_with_increment_only: false
  # min_increment: 0                        # Minimum amount of increment to accept a challenge.
  # max_increment: 180                      # Maximum amount of increment to accept a challenge.
  # min_initial: 0                          # Minimum amount of initial time to accept a challenge.
  # max_initial: 315360000                  # Maximum amount of initial time to accept a challenge.
  variants: # Chess variants to accept (https://lichess.org/variant).
    - standard
    - chess960
    #   - fromPosition
    - antichess
    - atomic
    - crazyhouse
    - horde
    - kingOfTheHill
    - racingKings
    - threeCheck
  time_controls: # Speeds or time controls in initial_minutes+increment_seconds format to accept.
    - bullet
    - blitz
    - rapid
  #   - classical
  #   - 25+0
  bot_modes: # Game modes to accept against BOTs.
    - casual # Unrated games.
    - rated # Rated games
  human_modes: # Game modes to accept against humans.
    - casual # Unrated games.
    - rated # Rated games

rematch:
  enabled: true # Enable rematch functionality.
  max_consecutive: 4 # Maximum consecutive rematches with same opponent.
  offer_on_win: true # Offer rematch when we win.
  offer_on_loss: true # Offer rematch when we lose.
  offer_on_draw: true # Offer rematch on draws.
  against_humans: false # Offer rematches against human players.
  against_bots: true # Offer rematches against bot players.
  delay_seconds: 1 # Delay before offering rematch (seconds).
  timeout_seconds: 30 # Timeout for rematch challenges (seconds).
# min_rating_diff: 0                      # Minimum rating difference to offer rematch.
# max_rating_diff: 300                    # Maximum rating difference to offer rematch.

messages:
  greeting: "Hey! I'm TacticalBot. Good luck!"
  goodbye: "Good game!"
  greeting_spectators: "Hey! I'm TacticalBot."
  goodbye_spectators: "Thanks for watching!"

whitelist: []
blacklist: []

books:
  HyperBullet: "./books/hyperbullet.bin"
  Bullet: "./books/bullet.bin"
  Blitz: "./books/big_blitz.bin"
  EngineTheory: "./books/engine_theory.bin"
  DefaultBook: "./books/DefaultBook.bin"
  PerfectBook: "./books/perfect_book.bin"
  StockfishBook: "./books/sfbook.bin"
  Optimus: "./books/OPTIMUS2502.bin"
  Stay: "./books/terimakichud.bin"
  White: "./books/white.bin"
  Black: "./books/black.bin"
  Win: "./books/win.bin"
